# Deploys the API portion of the application to Azure.
# See: https://github.com/marketplace/actions/azure-functions-action
name: Build and Deploy API

on:
  workflow_dispatch:

# CONFIGURATION
env:
  AZURE_FUNCTIONAPP_NAME: CovidCureIdApp  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './server/CovidCureIdApp'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.409'              # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNC_PUBLISH_PROFILE }} # Obtain from Azure portal and paste into GH Secrets

# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
